/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/tool'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EsRouteImport } from './routes/es'
import { Route as EnRouteImport } from './routes/en'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsDashboardRouteImport } from './routes/es.dashboard'
import { Route as EnDashboardRouteImport } from './routes/en.dashboard'
import { Route as BlogComoCriarApostilasInterativasPdfRouteImport } from './routes/blog.como-criar-apostilas-interativas-pdf'

const ToolRoute = ToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsDashboardRoute = EsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EsRoute,
} as any)
const EnDashboardRoute = EnDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EnRoute,
} as any)
const BlogComoCriarApostilasInterativasPdfRoute =
  BlogComoCriarApostilasInterativasPdfRouteImport.update({
    id: '/blog/como-criar-apostilas-interativas-pdf',
    path: '/blog/como-criar-apostilas-interativas-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tool': typeof ToolRoute
  '/blog/como-criar-apostilas-interativas-pdf': typeof BlogComoCriarApostilasInterativasPdfRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/es/dashboard': typeof EsDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tool': typeof ToolRoute
  '/blog/como-criar-apostilas-interativas-pdf': typeof BlogComoCriarApostilasInterativasPdfRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/es/dashboard': typeof EsDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/en': typeof EnRouteWithChildren
  '/es': typeof EsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tool': typeof ToolRoute
  '/blog/como-criar-apostilas-interativas-pdf': typeof BlogComoCriarApostilasInterativasPdfRoute
  '/en/dashboard': typeof EnDashboardRoute
  '/es/dashboard': typeof EsDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/en'
    | '/es'
    | '/sitemap.xml'
    | '/tool'
    | '/blog/como-criar-apostilas-interativas-pdf'
    | '/en/dashboard'
    | '/es/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/en'
    | '/es'
    | '/sitemap.xml'
    | '/tool'
    | '/blog/como-criar-apostilas-interativas-pdf'
    | '/en/dashboard'
    | '/es/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/en'
    | '/es'
    | '/sitemap.xml'
    | '/tool'
    | '/blog/como-criar-apostilas-interativas-pdf'
    | '/en/dashboard'
    | '/es/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EnRoute: typeof EnRouteWithChildren
  EsRoute: typeof EsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolRoute: typeof ToolRoute
  BlogComoCriarApostilasInterativasPdfRoute: typeof BlogComoCriarApostilasInterativasPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool': {
      id: '/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/dashboard': {
      id: '/es/dashboard'
      path: '/dashboard'
      fullPath: '/es/dashboard'
      preLoaderRoute: typeof EsDashboardRouteImport
      parentRoute: typeof EsRoute
    }
    '/en/dashboard': {
      id: '/en/dashboard'
      path: '/dashboard'
      fullPath: '/en/dashboard'
      preLoaderRoute: typeof EnDashboardRouteImport
      parentRoute: typeof EnRoute
    }
    '/blog/como-criar-apostilas-interativas-pdf': {
      id: '/blog/como-criar-apostilas-interativas-pdf'
      path: '/blog/como-criar-apostilas-interativas-pdf'
      fullPath: '/blog/como-criar-apostilas-interativas-pdf'
      preLoaderRoute: typeof BlogComoCriarApostilasInterativasPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnRouteChildren {
  EnDashboardRoute: typeof EnDashboardRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnDashboardRoute: EnDashboardRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface EsRouteChildren {
  EsDashboardRoute: typeof EsDashboardRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsDashboardRoute: EsDashboardRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EnRoute: EnRouteWithChildren,
  EsRoute: EsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolRoute: ToolRoute,
  BlogComoCriarApostilasInterativasPdfRoute:
    BlogComoCriarApostilasInterativasPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
